ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'ABSENCE_COMMENTED';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'MESSAGE_RECEIVED';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'CONVERSATION_ADDED';